modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/AntMCDev/MCLangsplit/issues"

[[mods]]
modId="mclangsplit"
version="${version}"
displayName="MC Langsplit"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mclangsplit"
logoFile="icon.png"
authors="AntMcDev"
description='''
A client-side dual language mod
'''

[[dependencies.mclangsplit]]
   modId="forge"
   mandatory=true
   versionRange="[46,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.mclangsplit]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"
